### ISSUE TITLE
API from README is not available

### ISSUE THREAD

**Issue by nvzoll** [click-connector/clickconnector-widget-sdk#2]
With package installed from [npm](https://www.npmjs.com/package/@clickconnector/widget-sdk?activeTab=readme) v0.0.7

![Screenshot 2024-12-16 152733](https://github.com/user-attachments/assets/dc8a9f2f-a1cb-4ef8-86a1-f5631ccfdf94)

**Comment by nvzoll** [comment]
+ logActivity arg type is mismatched with official snippet
+ Not clear which types can be for logActivity.

**Comment by click-connector** [comment]
Published New NPM Version@0.0.8 with updated typing and TS Doc - @nvzoll 

logActivity - Type can be any valid string and it is optional.
